version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: my-selenium-grid
    shm_size: 2g
    ports:
      - "4444:4444"  # Selenium Grid Hub
      - "7900:7900"  # VNC for visual debugging (optional)
    networks:
      - my-selenium-network

  my-app:
    build: .
    container_name: my-selenium-app
    ports:
      - "5000:5000"
    depends_on:
      - selenium
    networks:
      - my-selenium-network

networks:
  my-selenium-network:
    driver: bridge
